require: rubocop-rails

AllCops:
  Include:
    - 'app/**/*.rb'
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
