require: rubocop-rails

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'Gemfile'
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Layout/LineLength:
  Max: 120
